TOOL_SCHEMAS = {
    "dream": {
        "required": ["description"],
        "allowed_params": {
            "description", "num", "mode", "max_tags", "steps", "cfg_scale", "sampler",
            "seed", "width", "height", "negative_prompt", "loras", "min_artists", "max_artists",
        },
        "context_policy": "last_dream_or_none",
        "description": "调用 SD API 生成图片，基于描述和 Danbooru 标签组合。",
        "triggers": ["画", "生成", "出图", "涩图", "dream"],
        "param_hints": {
            "description": "必填。用户的绘图需求描述；如果来自 prompt choice，应是完整可执行的细化描述，保留用户指定内容，差异集中在构图/姿态/表情/场景/镜头重点/强度，不以画风为主要维度。",
            "num": "生成张数。",
            "mode": "模式: combo(默认)/single。",
            "max_tags": "最大标签数，默认留空。",
            "loras": "LoRA模型列表，仅允许 SD WebUI /sdapi/v1/loras 中的真实 LoRA 名称；不要填写 skill 名称。",
        },
    },
    "models": {
        "required": ["action"],
        "allowed_params": {"action", "role", "model"},
        "context_policy": "no_history",
        "terminal": True,
        "description": "查看/切换模型。action=status 查当前；action=list 列所有；action=switch 切换。",
        "triggers": ["切换模型", "查模型", "模型状态", "当前模型"],
        "param_hints": {
            "action": "必填: status/list/switch。",
            "role": "切换时: chat/vision。",
            "model": "切换时: 模型 key。",
        },
        "examples": [
            {
                "user": "切换聊天模型到 deepseek",
                "action": "models",
                "params": {"action": "switch", "role": "chat", "model": "deepseek-v4-flash-free"},
            },
        ],
    },
    "tagsite": {
        "required": ["names"],
        "allowed_params": {"names"},
        "context_policy": "no_history",
        "terminal": True,
        "description": "在 tagsite 上搜索角色/人物标签。",
        "triggers": ["搜索角色", "查角色", "找角色", "查tag", "搜索标签"],
        "param_hints": {"names": "必填。角色/标签名称列表。"},
    },
    "add_provider": {
        "required": ["base_url"],
        "allowed_params": {"base_url", "api_key", "provider_name", "capabilities", "switch_role"},
        "context_policy": "no_history",
        "description": "添加 OpenAI-compatible 模型服务商，并通过 /v1/models 自动发现模型。",
        "triggers": ["添加服务商", "接入 API", "添加模型渠道", "新的模型服务提供商", "provider", "base_url"],
        "param_hints": {
            "base_url": "必填。http:// 或 https:// 开头的服务地址，可带 /v1。",
            "api_key": "可选。sk- 开头或用户给出的 token，只能放 params.api_key，禁止写进 reply。",
            "provider_name": "可选。没有明确名称时系统会从 host 自动生成。",
            "capabilities": "可选。默认 [\"chat\"]；识图模型使用 [\"chat\", \"vision\"]。",
            "switch_role": "可选。用户说添加后直接使用/切换到它时填 chat 或 vision。",
        },
        "examples": [
            {
                "user": "添加新的服务商 http://192.168.0.107:1234/v1 sk-lm-xxx",
                "action": "add_provider",
                "params": {
                    "base_url": "http://192.168.0.107:1234/v1",
                    "api_key": "sk-lm-xxx",
                    "capabilities": ["chat"],
                    "switch_role": "chat",
                },
            },
            {
                "user": "接入这个 API https://api.example.com/v1 key 是 sk-xxx，作为识图模型",
                "action": "add_provider",
                "params": {
                    "base_url": "https://api.example.com/v1",
                    "api_key": "sk-xxx",
                    "capabilities": ["chat", "vision"],
                    "switch_role": "vision",
                },
            },
        ],
        "sensitive_params": ["api_key"],
    },
    "run": {
        "required": [],
        "allowed_params": {"mode", "num", "width", "height", "steps", "cfg_scale", "seed", "sampler", "loras"},
        "context_policy": "no_history",
    },
    "loras": {
        "required": [],
        "allowed_params": {"search", "lora_action", "name", "trigger"},
        "context_policy": "no_history",
        "terminal": True,
        "description": "列出/搜索 LoRA 模型，或管理 LoRA 触发词。",
        "triggers": ["lora", "LoRA"],
        "param_hints": {
            "search": "搜索关键词。",
            "lora_action": "操作: list(默认)/triggers/set-trigger。",
            "name": "lora 名称。",
            "trigger": "触发词。",
        },
    },
    "telegram": {
        "required": [],
        "allowed_params": {"subaction", "token"},
        "context_policy": "no_history",
        "terminal": True,
        "description": "启动/停止/查看 Telegram Bot。",
        "triggers": ["telegram", "tg"],
        "param_hints": {"subaction": "start/stop/status。"},
    },
    "status": {
        "required": [], "allowed_params": set(), "context_policy": "system_state",
        "terminal": True,
        "description": "查看系统状态。",
        "triggers": ["状态", "status"],
    },
    "history": {
        "required": [], "allowed_params": {"last", "search"}, "context_policy": "system_state",
        "terminal": True,
        "description": "查看对话历史。",
        "triggers": ["历史", "history"],
        "param_hints": {"last": "最近 N 条。", "search": "搜索关键词。"},
    },
    "artists": {
        "required": [], "allowed_params": {"search", "count_only"}, "context_policy": "system_state",
        "terminal": True,
        "description": "列出或搜索艺术家。",
        "triggers": ["艺术家", "artist"],
    },
    "gallery": {
        "required": [], "allowed_params": {"run", "list_only", "regenerate", "open_after"}, "context_policy": "system_state",
        "terminal": True,
        "description": "查看/打开最新生成图片的画廊。",
        "triggers": ["打开画廊", "看看结果", "查看结果", "gallery"],
        "param_hints": {
            "open_after": "可选。true 则在显示后自动用系统默认程序打开。",
            "list_only": "true 只列出不显示。",
            "regenerate": "重新生成索引后显示。",
        },
    },
    "generation_info": {
        "required": [], "allowed_params": {"detail"}, "context_policy": "last_dream_or_none",
        "terminal": True,
        "description": "查看上一张/刚才生成图片的完整提示词、生成参数或输出目录。",
        "triggers": ["完整提示词", "提示词", "这张", "上一张", "刚才生成", "生成参数", "输出目录"],
        "param_hints": {"detail": "prompt(默认)/params/path。"},
    },
    "webui": {
        "required": [], "allowed_params": {"host", "port", "background"}, "context_policy": "no_history",
        "terminal": True,
        "description": "启动 WebUI 控制界面。",
        "triggers": ["webui", "网页", "web界面"],
    },
    "update": {
        "required": [], "allowed_params": {"apply", "deps", "remote", "branch"}, "context_policy": "no_history",
        "terminal": True,
        "description": "检查或拉取 GitHub 远程仓库更新。apply=false 只检查；apply=true 执行 git pull --ff-only。",
        "triggers": ["更新程序", "检查更新", "拉取更新", "升级", "update"],
        "param_hints": {
            "apply": "true 表示实际更新；false 或省略表示只检查。",
            "deps": "true 表示更新后执行 pip install -r requirements.txt。默认 false。",
            "remote": "Git remote 名称，默认 origin。",
            "branch": "Git 分支，默认 main。",
        },
    },
    "config_get": {
        "required": ["key"], "allowed_params": {"key"}, "context_policy": "no_history",
        "terminal": True,
        "description": "读取配置项。",
        "triggers": ["配置", "config"],
    },
    "config_set": {"required": ["key", "value"], "allowed_params": {"key", "value"}, "context_policy": "no_history"},
    "clear": {
        "required": [], "allowed_params": {"target"}, "context_policy": "no_history",
        "description": "清理输出目录或历史记录。target 可以是 outputs 或 history。destructive 操作。",
        "triggers": ["清理", "清空", "删除 output"],
        "param_hints": {"target": "outputs 或 history。"},
    },
    "llm_test": {"required": [], "allowed_params": {"key", "value"}, "context_policy": "no_history"},
    "llm_status": {
        "required": [], "allowed_params": {"key", "value"}, "context_policy": "no_history",
        "terminal": True,
    },
    "session_new": {
        "required": [], "allowed_params": {"name"}, "context_policy": "no_history",
        "terminal": True,
    },
    "session_list": {
        "required": [], "allowed_params": set(), "context_policy": "no_history",
        "terminal": True,
        "description": "列出所有会话。",
        "triggers": ["会话", "session", "对话列表"],
    },
    "session_switch": {"required": ["target"], "allowed_params": {"target"}, "context_policy": "no_history"},
    "session_rename": {"required": ["name"], "allowed_params": {"name"}, "context_policy": "no_history"},
    "file_read": {
        "required": ["path"], "allowed_params": {"path", "start_line", "max_lines"}, "context_policy": "no_history",
        "description": "读取文件内容。用于查看代码/日志。",
        "param_hints": {"path": "文件路径。", "start_line": "从第几行开始。", "max_lines": "最多读几行。"},
        "sensitive_params": [],
    },
    "file_write": {"required": ["path", "content"], "allowed_params": {"path", "content", "confirm_yes"}, "context_policy": "no_history"},
    "file_list": {
        "required": [], "allowed_params": {"path", "pattern", "max_count"}, "context_policy": "no_history",
        "terminal": True,
    },
    "file_delete": {"required": ["path"], "allowed_params": {"path", "confirm_yes"}, "context_policy": "no_history"},
    "file_find": {
        "required": [], "allowed_params": {"pattern", "contains", "max_count"}, "context_policy": "no_history",
        "terminal": True,
    },
    "web_fetch": {
        "required": ["url"], "allowed_params": {"url", "format", "max_length"}, "context_policy": "no_history",
        "description": "抓取网页内容。用于查阅文档/信息。",
        "triggers": ["搜索", "查一下", "什么"],
        "param_hints": {"url": "http:// 或 https:// 开头的网址。", "format": "text(默认)/markdown/html。"},
    },
    "critique": {"required": [], "allowed_params": {"path", "expected"}, "context_policy": "last_tool_result"},
    "skill_list": {
        "required": [], "allowed_params": set(), "context_policy": "no_history",
        "terminal": True,
        "description": "列出所有可用 skill。",
        "triggers": ["skill", "技能"],
    },
    "skill_load": {"required": ["name"], "allowed_params": {"name", "params"}, "context_policy": "no_history"},
    "skill_create": {
        "required": ["name"],
        "allowed_params": {"name", "description", "triggers", "chain_template", "body"},
        "context_policy": "no_history",
    },
    "tags": {
        "required": ["keyword"],
        "allowed_params": {"keyword", "type"},
        "context_policy": "no_history",
        "terminal": True,
    },
    "memory_set": {
        "required": ["key", "value"],
        "allowed_params": {"key", "value"},
        "description": "保存一条信息到跨会话的长期记忆中。由你主动调用，当发现值得记住的信息时。",
        "triggers": ["记住", "保存", "记忆", "记一下"],
        "param_hints": {
            "key": "记忆键名，自由命名。建议英文+下划线，如 user_name、preferred_style",
            "value": "要记住的事实或信息，尽量完整保留用户原话",
        },
        "terminal": True,
        "examples": [
            {"user": "我喜欢 portrait 模式", "action": "memory_set",
             "params": {"key": "preferred_style", "value": "portrait"}},
        ],
    },
    "memory_get": {
        "required": ["key"],
        "allowed_params": {"key"},
        "description": "读取一条记忆并告知用户。用户问你还记不记得时查证后回复。",
        "triggers": ["记得吗", "还记得", "查记忆", "我上次说过"],
        "param_hints": {"key": "要查询的记忆键名"},
        "terminal": True,
    },
    "memory_forget": {
        "required": ["key"],
        "allowed_params": {"key", "confirm"},
        "description": "删除一条记忆。用户明确要求忘掉时使用。",
        "triggers": ["忘了", "删除记忆", "忘掉"],
        "param_hints": {
            "key": "要删除的记忆键名",
            "confirm": "用户已确认删除时传 yes，否则不传",
        },
        "terminal": True,
    },
    "memory_list": {
        "required": [],
        "allowed_params": set(),
        "description": "列出苏丹娜记忆中所有与当前用户相关的信息。用户问'你记得什么'时使用。",
        "terminal": True,
        "triggers": ["你记得什么", "有什么记忆", "你都知道什么"],
    },
    "chat": {
        "required": ["reply"],
        "allowed_params": set(),
        "context_policy": "short_chat_history",
    },
}
